name: dona-dev
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dona
      - POSTGRES_USER=dona
      - POSTGRES_PASSWORD=password

volumes:
  postgres-data: {}
